#!/usr/bin/env bash

#Java fix to allow jetbrains IDE's to run
wmname LG3D

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

monitors="$(xrandr --listactivemonitors | awk '{if (NR!=1) {print}}' | sed -e 's/^.* //')"
nonPrimaryMonitors="$(xrandr --listactivemonitors --noprimary | awk '{if (NR!=1) {print}}' | sed -e 's/^.* //')"
for monitor in $monitors ; do
    if $(echo $monitor | grep $nonPrimaryMonitors 2>/dev/null) ; then
	nonPrimaryMonitorsPrime="$nonPrimaryMonitorsPrime $monitor"
    else
	primaryMonitor="$monitor"
    fi
done

bspc monitor $primaryMonitor -d I II III IV V VI VII VIII IX X
for monitor in $nonPrimaryMonitorsPrime ; do
    bspc $monitor DP1 -d external-$monitor
done
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a mplayer2 state=floating
bspc rule -a Tilda manage=on state=floating follow=on focus=on border=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Turn off the fucking terminal bell
# that insists on working even if sound is off
xset -b

#start sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Other autostart programs
which emacs >/dev/null 2>/dev/null && emacs --daemon 					&
which compton >/dev/null 2>/dev/null && compton --config ~/.config/compton.conf		&
which dropbox >/dev/null 2>/dev/null && dropbox 					&
which libinput-gestures-setup >/dev/null 2>/dev/null && libinput-gestures-setup start   &
which feh >/dev/null 2>/dev/null && feh --randomize --bg-scale ~/.config/desktopBgs/*	&
which redshift >/dev/null 2>/dev/null && redshift                                       &
which tilda >/dev/null 2>/dev/null && sleep 4 && tilda 					&
