{ config, lib, pkgs, ... }:

{
  home.packages = with pkgs; [ vim ];

  home.file.".vimrc".text = ''
    """ This file autogenerated by:
    """ ${config.xdg.configHome}/nixpkgs/program-cfg/vim.nix
    """ This file should not be edited
  '' + builtins.readFile ./vimrc.vim;
}
